# Generated by Django 2.2.24 on 2021-06-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
