# Generated by Django 2.2.24 on 2021-06-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(null=True, related_name='materias', to='materias.Materia'),
        ),
    ]
