# Generated by Django 2.2.24 on 2021-06-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(null=True, related_name='estudiantes', to='materias.Materia'),
        ),
    ]
